# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/bradp/OneDrive/Documents/GitHub/545_Melons/Lab3/Lab3/Lab3.cache/wt [current_project]
set_property parent.project_path C:/Users/bradp/OneDrive/Documents/GitHub/545_Melons/Lab3/Lab3/Lab3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/bradp/OneDrive/Documents/GitHub/545_Melons/Lab3/Lab3/Lab3.srcs/sources_1/new/PCMtoPWM.sv
  C:/Users/bradp/OneDrive/Documents/GitHub/545_Melons/Lab1/lab1_alter.sv
}
read_verilog -library xil_defaultlib C:/Users/bradp/OneDrive/Documents/GitHub/545_Melons/Lab3/Lab3/Lab3.srcs/sources_1/new/sd_controller.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/bradp/OneDrive/Documents/GitHub/545_Melons/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/bradp/OneDrive/Documents/GitHub/545_Melons/Nexys4DDR_Master.xdc]


synth_design -top lab1 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef lab1.dcp

catch { report_utilization -file lab1_utilization_synth.rpt -pb lab1_utilization_synth.pb }
