# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ROM_Handler_Top/ROM_Handler_Top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_Handler_Top || ORIG_REF_NAME==ROM_Handler_Top}]

# IP: bd/ROM_Handler_Top/ip/ROM_Handler_Top_blk_mem_gen_0_0/ROM_Handler_Top_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_Handler_Top_blk_mem_gen_0_0 || ORIG_REF_NAME==ROM_Handler_Top_blk_mem_gen_0_0}]

# IP: bd/ROM_Handler_Top/ip/ROM_Handler_Top_ROM_Handler_0_1/ROM_Handler_Top_ROM_Handler_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_Handler_Top_ROM_Handler_0_1 || ORIG_REF_NAME==ROM_Handler_Top_ROM_Handler_0_1}]

# XDC: bd/ROM_Handler_Top/ip/ROM_Handler_Top_blk_mem_gen_0_0/ROM_Handler_Top_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/ROM_Handler_Top/ROM_Handler_Top_ooc.xdc
